/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const FileType = IDL.Variant({ 'video' : IDL.Null, 'photo' : IDL.Null });
export const MediaItem = IDL.Record({
  'studentId' : IDL.Nat,
  'fileType' : FileType,
  'timestamp' : IDL.Text,
  'caption' : IDL.Text,
  'blobReferenceId' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'studentId' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMedia' : IDL.Func([MediaItem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMedia' : IDL.Func([IDL.Text], [], []),
  'getAllKeys' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllMedia' : IDL.Func([], [IDL.Vec(MediaItem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getData' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getMedia' : IDL.Func([IDL.Text], [IDL.Opt(MediaItem)], ['query']),
  'getMediaByStudentId' : IDL.Func([IDL.Nat], [IDL.Vec(MediaItem)], ['query']),
  'getMediaByType' : IDL.Func(
      [IDL.Nat, FileType],
      [IDL.Vec(MediaItem)],
      ['query'],
    ),
  'getStudentMediaCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setData' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateCaption' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const FileType = IDL.Variant({ 'video' : IDL.Null, 'photo' : IDL.Null });
  const MediaItem = IDL.Record({
    'studentId' : IDL.Nat,
    'fileType' : FileType,
    'timestamp' : IDL.Text,
    'caption' : IDL.Text,
    'blobReferenceId' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'studentId' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMedia' : IDL.Func([MediaItem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMedia' : IDL.Func([IDL.Text], [], []),
    'getAllKeys' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllMedia' : IDL.Func([], [IDL.Vec(MediaItem)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getData' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getMedia' : IDL.Func([IDL.Text], [IDL.Opt(MediaItem)], ['query']),
    'getMediaByStudentId' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MediaItem)],
        ['query'],
      ),
    'getMediaByType' : IDL.Func(
        [IDL.Nat, FileType],
        [IDL.Vec(MediaItem)],
        ['query'],
      ),
    'getStudentMediaCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setData' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateCaption' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };